# Generated by Django 3.1.5 on 2023-09-16 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
        ('products', '0009_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('delivery_charge', models.FloatField(default=0)),
                ('payment_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.CharField(blank=True, max_length=80, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Placed', 'Placed'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=40)),
                ('transaction_status', models.CharField(choices=[('Waiting', 'Waiting'), ('PENDING', 'PENDING'), ('TXN_SUCCESS', 'TXN_SUCCESS'), ('TXN_FAILURE', 'TXN_FAILURE')], default='Waiting', max_length=40)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='addresses.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('extra', models.CharField(blank=True, max_length=80, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.price')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
