# Generated by Django 3.1.5 on 2021-06-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210602_2102'),
        ('products', '0005_remove_product_slug'),
        ('orders', '0001_initial'),
    ]

    operations = [
        
        
       
    ]
