# Generated by Django 3.1.5 on 2021-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210604_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
