# Generated by Django 3.1.5 on 2022-01-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_courier'),
        ('addresses', '0005_auto_20220101_1625'),
        ('orders', '0003_orderitem_extra'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
        
    ]
