# Generated by Django 3.1.4 on 2020-12-24 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('sent', models.DateTimeField(auto_now=True, null=True, verbose_name='sent')),
                ('otp', models.CharField(max_length=8, unique=True, verbose_name='OTP')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone OTP confirmation',
                'verbose_name_plural': 'Phone OTP confirmations',
            },
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
