# Generated by Django 3.1.3 on 2021-01-07 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201224_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=33, verbose_name='Phone Number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('sent', models.DateTimeField(auto_now=True, null=True, verbose_name='sent')),
                ('otp', models.CharField(max_length=8, unique=True, verbose_name='OTP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTP',
            },
        ),
    ]
