# Generated by Django 3.1.3 on 2021-01-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_onetimepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneConfirmation',
        ),
    ]
