# Generated by Django 3.1.1 on 2020-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
