# Generated by Django 3.1.5 on 2021-06-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
