# Generated by Django 3.1.1 on 2020-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201027_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='product/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(verbose_name='M.R.P.'),
        ),
    ]
