# Generated by Django 3.1.5 on 2021-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210926_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='weight',
            field=models.FloatField(blank=True, default=200, null=True),
        ),
    ]
